Cu 86cv4e9a3 onboarding api
ANCKR/rmr_web pull request #20
Opened 2024-04-22 10:38 UTC by anal-anckr

pr for : https://app.clickup.com/t/86cv4e9a3
 
 changes: 
 1. truevault folder & inside that files created which contain the true vault crud functions.
 2. onboarding api is created.
 3. send email api is created. (need to be develop further)
 4. middleware file chnages takes place
 5. responce file changes takes place

2024-04-22 11:00 UTC, akshayAnckr requested changes

2024-04-22 11:00 UTC, akshayAnckr commented on src/app/responce.ts
>      message:string,
@anal-anckr file name typo issue : it should be 'response.ts'

2024-04-23 08:31 UTC, vishal-anckr requested changes
Remove console from PR

2024-04-23 12:03 UTC, vishal-anckr commented
@anal-anckr All checks failed. Please fix

2024-04-23 12:57 UTC, vishal-anckr requested changes
@anal-anckr Few mistakes we need to improve:
- Unused commented code
- Inconsistency in string response message.

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/api/orgReferral/create/route.ts
> +    // if (orgReferralData) {
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/api/orgReferral/create/route.ts
> +    //   if(checkOrgCodeExistance){
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/truevault/groups/adduser-group.ts
> +    // console.error('Error adding group members:', error);
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/truevault/groups/create-group.ts
> +    // console.error('Error creating group:', error);
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/truevault/groups/delete-group.ts
> +      // console.error('Error deleting group:', error);
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/truevault/groups/read-group.ts
> +    // console.error('Error retrieving group:', error);
@anal-anckr Commented code should be removed

2024-04-23 12:57 UTC, vishal-anckr commented on src/app/truevault/groups/update-group.ts
> +    // console.error('Error updating group:', error);
@anal-anckr Commented code should be removed

2024-04-23 13:20 UTC, anal-anckr commented on src/app/api/orgReferral/create/route.ts
> +    // if (orgReferralData) {
no that code has to be there, for future reference

2024-04-23 13:21 UTC, anal-anckr commented on src/app/api/orgReferral/create/route.ts
> +    // if (orgReferralData) {
after sprint /milestone 4 ,after knowing the admin panel scope( if any) i will delete that code

2024-04-23 13:57 UTC, merged